-- Supabase schema for importing supabase_trips_import.csv into public.trips.
-- Run supabase_schema.sql first so public.vehicles and public.drivers exist.
-- CSV headers:
-- record_date, ism_no, shipment_date, time_in, time_out, origin, destination,
-- plate_no, load_details, driver_name, trip_fuel, route, trip_date
--
-- Existing trip rows and IDs are preserved. CSV-only rows may leave vehicle_id
-- and driver_id empty; source plate and driver values are kept in plate_no and
-- driver_name.

create table if not exists public.trips (
    id bigint generated by default as identity primary key,
    record_date date,
    ism_no text,
    shipment_date date not null default current_date,
    time_in time without time zone,
    time_out time without time zone,
    origin text,
    destination text,
    plate_no text,
    load_details text,
    driver_name text,
    trip_fuel text,
    route text,
    trip_date date,
    vehicle_id bigint references public.vehicles(id) on delete set null,
    driver_id bigint references public.drivers(id) on delete set null,
    start_odometer bigint check (start_odometer >= 0),
    end_odometer bigint,
    notes text,
    constraint trips_csv_odometer_order_check check (
        start_odometer is null
        or end_odometer is null
        or end_odometer >= start_odometer
    )
);

alter table public.trips
    add column if not exists record_date date,
    add column if not exists ism_no text,
    add column if not exists shipment_date date,
    add column if not exists time_in time without time zone,
    add column if not exists time_out time without time zone,
    add column if not exists origin text,
    add column if not exists destination text,
    add column if not exists plate_no text,
    add column if not exists load_details text,
    add column if not exists driver_name text,
    add column if not exists trip_fuel text;

update public.trips
set shipment_date = trip_date
where shipment_date is null and trip_date is not null;

update public.trips
set shipment_date = current_date
where shipment_date is null;

alter table public.trips
    alter column shipment_date set default current_date,
    alter column shipment_date set not null,
    alter column vehicle_id drop not null,
    alter column driver_id drop not null,
    alter column route drop not null,
    alter column start_odometer drop not null,
    alter column end_odometer drop not null,
    alter column trip_date drop not null;

alter table public.trips drop constraint if exists trips_vehicle_id_fkey;
alter table public.trips
    add constraint trips_vehicle_id_fkey
    foreign key (vehicle_id) references public.vehicles(id) on delete set null;

alter table public.trips drop constraint if exists trips_driver_id_fkey;
alter table public.trips
    add constraint trips_driver_id_fkey
    foreign key (driver_id) references public.drivers(id) on delete set null;

update public.trips as t
set plate_no = v.plate_number
from public.vehicles as v
where t.vehicle_id = v.id and t.plate_no is null;

update public.trips as t
set driver_name = d.name
from public.drivers as d
where t.driver_id = d.id and t.driver_name is null;

create index if not exists trips_shipment_date_idx
    on public.trips(shipment_date desc);
