create table if not exists public.vehicles (
    id bigint generated by default as identity primary key,
    plate_number text not null unique,
    make text not null,
    model text not null,
    year integer not null check (year >= 1900),
    color text,
    status text not null default 'available',
    odometer bigint not null default 0 check (odometer >= 0),
    registration_expiry date,
    insurance_expiry date,
    created_at timestamptz not null default now()
);

create table if not exists public.drivers (
    id bigint generated by default as identity primary key,
    name text not null,
    license_number text not null unique,
    phone text,
    email text,
    status text not null default 'active',
    created_at timestamptz not null default now()
);

create table if not exists public.assignments (
    id bigint generated by default as identity primary key,
    driver_id bigint not null references public.drivers(id) on delete cascade,
    vehicle_id bigint not null references public.vehicles(id) on delete cascade,
    assigned_date date not null default current_date,
    returned_date date,
    notes text
);

create table if not exists public.maintenance (
    id bigint generated by default as identity primary key,
    vehicle_id bigint not null references public.vehicles(id) on delete cascade,
    service_type text not null,
    description text,
    cost numeric(12, 2) not null default 0 check (cost >= 0),
    performed_on date not null default current_date
);

create table if not exists public.fuel_logs (
    id bigint generated by default as identity primary key,
    vehicle_id bigint not null references public.vehicles(id) on delete cascade,
    fuel_type text not null,
    quantity numeric(12, 2) not null check (quantity > 0),
    price_per_liter numeric(12, 2) not null check (price_per_liter > 0),
    total_cost numeric(12, 2) not null check (total_cost >= 0),
    logged_on date not null default current_date
);

create table if not exists public.trips (
    id bigint generated by default as identity primary key,
    vehicle_id bigint references public.vehicles(id) on delete set null,
    driver_id bigint references public.drivers(id) on delete set null,
    record_date date,
    ism_no text,
    shipment_date date not null default current_date,
    time_in time without time zone,
    time_out time without time zone,
    origin text,
    destination text,
    plate_no text,
    load_details text,
    driver_name text,
    trip_fuel text,
    route text,
    start_odometer bigint check (start_odometer >= 0),
    end_odometer bigint check (
        start_odometer is null
        or end_odometer is null
        or end_odometer >= start_odometer
    ),
    trip_date date,
    notes text
);

create index if not exists assignments_vehicle_id_idx on public.assignments(vehicle_id);
create index if not exists assignments_driver_id_idx on public.assignments(driver_id);
create index if not exists maintenance_vehicle_id_idx on public.maintenance(vehicle_id);
create index if not exists fuel_logs_vehicle_id_idx on public.fuel_logs(vehicle_id);
create index if not exists trips_vehicle_id_idx on public.trips(vehicle_id);
create index if not exists trips_driver_id_idx on public.trips(driver_id);
create index if not exists trips_shipment_date_idx on public.trips(shipment_date desc);

alter table public.vehicles enable row level security;
alter table public.drivers enable row level security;
alter table public.assignments enable row level security;
alter table public.maintenance enable row level security;
alter table public.fuel_logs enable row level security;
alter table public.trips enable row level security;
