alter table public.trips
    add column if not exists created_by uuid references auth.users(id) on delete set null;

alter table public.fuel_logs
    add column if not exists created_by uuid references auth.users(id) on delete set null;

alter table public.maintenance
    add column if not exists created_by uuid references auth.users(id) on delete set null;

alter table public.trips
    add column if not exists manifest_object_path text;

alter table public.trips
    add column if not exists last_edited_by uuid references auth.users(id) on delete set null;

alter table public.trips
    add column if not exists last_edited_by_email text;

alter table public.fuel_logs
    add column if not exists invoice_object_path text;

create table if not exists public.trip_edit_history (
    id bigint generated by default as identity primary key,
    trip_id bigint not null references public.trips(id) on delete cascade,
    edited_by uuid references auth.users(id) on delete set null,
    edited_by_email text,
    edited_at timestamptz not null default now(),
    old_values jsonb not null,
    new_values jsonb not null
);

create index if not exists trip_edit_history_trip_id_edited_at_idx
    on public.trip_edit_history(trip_id, edited_at desc);

alter table public.trip_edit_history enable row level security;

create or replace function public.log_trip_edit_history()
returns trigger
language plpgsql
set search_path = pg_catalog, public, pg_temp
as $$
declare
    old_snapshot jsonb;
    new_snapshot jsonb;
begin
    old_snapshot := to_jsonb(old) - array[
        'created_by', 'last_edited_by', 'last_edited_by_email'
    ];
    new_snapshot := to_jsonb(new) - array[
        'created_by', 'last_edited_by', 'last_edited_by_email'
    ];

    if old_snapshot is distinct from new_snapshot then
        insert into public.trip_edit_history (
            trip_id,
            edited_by,
            edited_by_email,
            old_values,
            new_values
        )
        values (
            new.id,
            new.last_edited_by,
            new.last_edited_by_email,
            old_snapshot,
            new_snapshot
        );
    end if;
    return new;
end;
$$;

drop trigger if exists trips_edit_history on public.trips;
create trigger trips_edit_history
    after update on public.trips
    for each row execute function public.log_trip_edit_history();

create index if not exists trips_created_by_idx on public.trips(created_by);
create index if not exists fuel_logs_created_by_idx on public.fuel_logs(created_by);
create index if not exists maintenance_created_by_idx on public.maintenance(created_by);
create index if not exists trips_created_by_shipment_date_idx
    on public.trips(created_by, shipment_date desc);
create index if not exists trips_shipment_date_idx
    on public.trips(shipment_date desc);
create index if not exists fuel_logs_created_by_logged_on_idx
    on public.fuel_logs(created_by, logged_on desc);
create index if not exists fuel_logs_logged_on_idx
    on public.fuel_logs(logged_on desc);
create index if not exists maintenance_created_by_performed_on_idx
    on public.maintenance(created_by, performed_on desc);
create index if not exists maintenance_performed_on_idx
    on public.maintenance(performed_on desc);
create index if not exists assignments_assigned_date_idx
    on public.assignments(assigned_date desc);

select setval(
    pg_get_serial_sequence('public.trips', 'id'),
    coalesce(max(id), 1),
    max(id) is not null
)
from public.trips;

select setval(
    pg_get_serial_sequence('public.fuel_logs', 'id'),
    coalesce(max(id), 1),
    max(id) is not null
)
from public.fuel_logs;

select setval(
    pg_get_serial_sequence('public.maintenance', 'id'),
    coalesce(max(id), 1),
    max(id) is not null
)
from public.maintenance;

create or replace function public.prevent_record_owner_change()
returns trigger
language plpgsql
as $$
begin
    if new.created_by is distinct from old.created_by then
        raise exception 'Record ownership cannot be changed';
    end if;
    return new;
end;
$$;

drop trigger if exists trips_owner_immutable on public.trips;
create trigger trips_owner_immutable
    before update of created_by on public.trips
    for each row execute function public.prevent_record_owner_change();

drop trigger if exists fuel_logs_owner_immutable on public.fuel_logs;
create trigger fuel_logs_owner_immutable
    before update of created_by on public.fuel_logs
    for each row execute function public.prevent_record_owner_change();

drop trigger if exists maintenance_owner_immutable on public.maintenance;
create trigger maintenance_owner_immutable
    before update of created_by on public.maintenance
    for each row execute function public.prevent_record_owner_change();

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'fleet-trip-documents',
    'fleet-trip-documents',
    false,
    52428800,
    array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;
