create table if not exists public.notifications (
    id bigint generated by default as identity primary key,
    recipient_user_id uuid references auth.users(id) on delete set null,
    actor_user_id uuid references auth.users(id) on delete set null,
    actor_name text not null,
    actor_email text not null default '',
    notification_type text not null,
    module text not null,
    record_id text not null,
    title text not null,
    message text not null,
    is_read boolean not null default false,
    created_at timestamptz not null default now(),
    read_at timestamptz
);

alter table public.notifications
    drop constraint if exists notifications_actor_module_record_type_unique;
alter table public.notifications
    drop constraint if exists notifications_recipient_module_record_type_unique;
alter table public.notifications
    add constraint notifications_recipient_module_record_type_unique
        unique (recipient_user_id, notification_type, module, record_id);

create index if not exists notifications_recipient_created_at_idx
    on public.notifications(recipient_user_id, created_at desc);

create index if not exists notifications_recipient_unread_idx
    on public.notifications(recipient_user_id, created_at desc)
    where is_read = false;

create or replace function public.protect_notification_audit_fields()
returns trigger
language plpgsql
set search_path = pg_catalog, public, pg_temp
as $$
begin
    if (to_jsonb(new) - array['is_read', 'read_at'])
        is distinct from (to_jsonb(old) - array['is_read', 'read_at']) then
        raise exception 'Notification audit details are immutable';
    end if;

    if old.is_read and (
        new.is_read is distinct from old.is_read
        or new.read_at is distinct from old.read_at
    ) then
        raise exception 'A read notification cannot be changed';
    end if;

    if not old.is_read and not new.is_read and new.read_at is distinct from old.read_at then
        raise exception 'Notification read time can only be set when marking it read';
    end if;

    if not old.is_read and new.is_read and new.read_at is null then
        raise exception 'Read notifications require a read timestamp';
    end if;
    if not old.is_read and new.is_read then
        new.read_at := now();
    end if;

    return new;
end;
$$;

drop trigger if exists notifications_audit_fields_immutable on public.notifications;
create trigger notifications_audit_fields_immutable
    before update on public.notifications
    for each row execute function public.protect_notification_audit_fields();

alter table public.notifications enable row level security;

revoke all on public.notifications from anon, authenticated;
grant select on public.notifications to authenticated;
grant update (is_read, read_at) on public.notifications to authenticated;
grant all on public.notifications to service_role;
grant usage, select on sequence public.notifications_id_seq to service_role;

drop policy if exists notifications_admin_select on public.notifications;
create policy notifications_admin_select
    on public.notifications
    for select
    to authenticated
    using (
        recipient_user_id = (select auth.uid())
        and (select auth.jwt() -> 'app_metadata' ->> 'role') = 'administrator'
        and (select auth.jwt() -> 'user_metadata' ->> 'role') is distinct from 'dispatcher'
    );

drop policy if exists notifications_admin_update on public.notifications;
create policy notifications_admin_update
    on public.notifications
    for update
    to authenticated
    using (
        recipient_user_id = (select auth.uid())
        and (select auth.jwt() -> 'app_metadata' ->> 'role') = 'administrator'
        and (select auth.jwt() -> 'user_metadata' ->> 'role') is distinct from 'dispatcher'
    )
    with check (
        recipient_user_id = (select auth.uid())
        and (select auth.jwt() -> 'app_metadata' ->> 'role') = 'administrator'
        and (select auth.jwt() -> 'user_metadata' ->> 'role') is distinct from 'dispatcher'
    );
