-- Payroll tables use existing drivers and trips; source trip rows are read-only
-- from the payroll workflow. Run after supabase_schema.sql and the trips schema.

create table if not exists public.payroll_periods (
    id bigint generated by default as identity primary key,
    start_date date not null,
    end_date date not null,
    status text not null default 'draft'
        check (status in ('draft', 'reviewed', 'finalized')),
    created_by uuid references auth.users(id) on delete set null,
    reviewed_by uuid references auth.users(id) on delete set null,
    finalized_by uuid references auth.users(id) on delete set null,
    created_at timestamptz not null default now(),
    reviewed_at timestamptz,
    finalized_at timestamptz,
    constraint payroll_period_dates_check check (start_date <= end_date),
    constraint payroll_period_range_unique unique (start_date, end_date)
);

create table if not exists public.payroll_items (
    id bigint generated by default as identity primary key,
    payroll_period_id bigint not null references public.payroll_periods(id) on delete restrict,
    trip_id bigint not null references public.trips(id) on delete restrict,
    driver_id bigint not null references public.drivers(id) on delete restrict,
    driver_name text not null,
    trip_date date not null,
    ism_no text not null,
    origin text not null,
    destination text not null,
    rate numeric(12, 2) not null check (rate in (200.00, 900.00)),
    created_at timestamptz not null default now(),
    constraint payroll_items_period_trip_unique unique (payroll_period_id, trip_id)
);

create table if not exists public.payroll_summaries (
    id bigint generated by default as identity primary key,
    payroll_period_id bigint not null references public.payroll_periods(id) on delete restrict,
    driver_id bigint not null references public.drivers(id) on delete restrict,
    driver_name text not null,
    total_trips integer not null check (total_trips >= 0),
    gross_pay numeric(12, 2) not null check (gross_pay >= 0),
    cash_advances numeric(12, 2) not null check (cash_advances >= 0),
    claims_total numeric(12, 2) not null default 0 check (claims_total >= 0),
    net_before_overdraft numeric(12, 2) not null,
    opening_overdraft numeric(12, 2) not null check (opening_overdraft >= 0),
    new_overdraft numeric(12, 2) not null check (new_overdraft >= 0),
    overdraft_deduction numeric(12, 2) not null check (overdraft_deduction >= 0),
    final_net_pay numeric(12, 2) not null check (final_net_pay >= 0),
    remaining_amount_due numeric(12, 2) not null check (remaining_amount_due >= 0),
    remaining_overdraft numeric(12, 2) not null check (remaining_overdraft >= 0),
    created_at timestamptz not null default now(),
    constraint payroll_summaries_period_driver_unique unique (payroll_period_id, driver_id)
);

create table if not exists public.cash_advances (
    id bigint generated by default as identity primary key,
    payroll_period_id bigint not null references public.payroll_periods(id) on delete restrict,
    driver_id bigint not null references public.drivers(id) on delete restrict,
    advance_date date not null,
    amount numeric(12, 2) not null check (amount > 0),
    remarks text,
    reference text,
    created_by uuid references auth.users(id) on delete set null,
    created_at timestamptz not null default now()
);

create unique index if not exists cash_advances_reference_unique
    on public.cash_advances(reference) where reference is not null;

create table if not exists public.overdraft_transactions (
    id bigint generated by default as identity primary key,
    driver_id bigint not null references public.drivers(id) on delete restrict,
    payroll_period_id bigint references public.payroll_periods(id) on delete restrict,
    transaction_type text not null
        check (transaction_type in ('opening', 'new', 'deduction')),
    amount numeric(12, 2) not null check (amount > 0),
    effective_date date not null,
    remarks text,
    created_by uuid references auth.users(id) on delete set null,
    created_at timestamptz not null default now()
);

create table if not exists public.payroll_audit (
    id bigint generated by default as identity primary key,
    payroll_period_id bigint references public.payroll_periods(id) on delete restrict,
    actor_id uuid references auth.users(id) on delete set null,
    action text not null,
    details jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

alter table public.payroll_summaries
    add column if not exists claims_total numeric(12, 2) not null default 0
    check (claims_total >= 0);
alter table public.payroll_audit alter column payroll_period_id drop not null;

create index if not exists payroll_items_period_driver_idx
    on public.payroll_items(payroll_period_id, driver_id);
create index if not exists payroll_items_trip_idx on public.payroll_items(trip_id);
create index if not exists cash_advances_period_driver_idx
    on public.cash_advances(payroll_period_id, driver_id);
create index if not exists overdraft_driver_date_idx
    on public.overdraft_transactions(driver_id, effective_date);

alter table public.payroll_periods enable row level security;
alter table public.payroll_items enable row level security;
alter table public.payroll_summaries enable row level security;
alter table public.cash_advances enable row level security;
alter table public.overdraft_transactions enable row level security;
alter table public.payroll_audit enable row level security;

create or replace function public.finalize_payroll_period(
    p_period_id bigint,
    p_actor_id uuid,
    p_settle_overdraft boolean default false
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
    selected_period public.payroll_periods%rowtype;
    item_row record;
    summary_row record;
    balance_before numeric(12, 2);
    deduction numeric(12, 2);
begin
    select * into selected_period
    from public.payroll_periods
    where id = p_period_id
    for update;

    if not found then
        raise exception 'Payroll period not found';
    end if;
    if selected_period.status <> 'reviewed' then
        raise exception 'Only reviewed payroll can be finalized';
    end if;

    -- Serialize finalization of overlapping periods on each shared trip.
    for item_row in
        select trip_id from public.payroll_items
        where payroll_period_id = p_period_id order by trip_id
    loop
        perform pg_advisory_xact_lock(hashtextext(item_row.trip_id::text));
    end loop;

    if exists (
        select 1
        from public.payroll_items current_item
        join public.payroll_items prior_item on prior_item.trip_id = current_item.trip_id
        join public.payroll_periods prior_period
          on prior_period.id = prior_item.payroll_period_id
        where current_item.payroll_period_id = p_period_id
          and prior_item.payroll_period_id <> p_period_id
          and prior_period.status = 'finalized'
    ) then
        raise exception 'A trip is already included in another finalized payroll';
    end if;

    delete from public.payroll_summaries where payroll_period_id = p_period_id;
    for summary_row in
        select d.id as driver_id, d.name as driver_name,
               count(pi.id)::integer as total_trips,
               coalesce(sum(pi.rate), 0)::numeric(12, 2) as gross_pay,
               coalesce((
                   select sum(ca.amount) from public.cash_advances ca
                   where ca.payroll_period_id = p_period_id and ca.driver_id = d.id
               ), 0)::numeric(12, 2) as cash_advances,
               coalesce((
                   select sum(ot.amount) from public.overdraft_transactions ot
                   where ot.driver_id = d.id and ot.effective_date <= selected_period.end_date
                     and ot.transaction_type in ('opening', 'new')
               ), 0)::numeric(12, 2) as overdraft_credits,
               coalesce((
                   select sum(ot.amount) from public.overdraft_transactions ot
                   where ot.driver_id = d.id and ot.effective_date <= selected_period.end_date
                     and ot.transaction_type = 'deduction'
               ), 0)::numeric(12, 2) as overdraft_debits
        from public.drivers d
        left join public.payroll_items pi
          on pi.driver_id = d.id and pi.payroll_period_id = p_period_id
        group by d.id, d.name
    loop
        balance_before := greatest(
            summary_row.overdraft_credits - summary_row.overdraft_debits, 0
        );
        deduction := 0;
        if p_settle_overdraft then
            deduction := least(
                greatest(summary_row.gross_pay - summary_row.cash_advances, 0),
                balance_before
            );
        end if;

        if deduction > 0 then
            insert into public.overdraft_transactions (
                driver_id, payroll_period_id, transaction_type, amount,
                effective_date, remarks, created_by
            ) values (
                summary_row.driver_id, p_period_id, 'deduction', deduction,
                selected_period.end_date, 'Payroll overdraft settlement', p_actor_id
            );
        end if;

        insert into public.payroll_summaries (
            payroll_period_id, driver_id, driver_name, total_trips, gross_pay,
            cash_advances, net_before_overdraft, opening_overdraft,
            new_overdraft, overdraft_deduction, final_net_pay,
            remaining_amount_due, remaining_overdraft
        ) values (
            p_period_id, summary_row.driver_id, summary_row.driver_name,
            summary_row.total_trips, summary_row.gross_pay,
            summary_row.cash_advances,
            summary_row.gross_pay - summary_row.cash_advances,
            coalesce((
                select sum(amount) from public.overdraft_transactions
                where driver_id = summary_row.driver_id
                  and effective_date <= selected_period.end_date
                  and transaction_type = 'opening'
            ), 0),
            coalesce((
                select sum(amount) from public.overdraft_transactions
                where driver_id = summary_row.driver_id
                  and effective_date <= selected_period.end_date
                  and transaction_type = 'new'
            ), 0),
            deduction,
            greatest(summary_row.gross_pay - summary_row.cash_advances - deduction, 0),
            greatest(summary_row.cash_advances - summary_row.gross_pay, 0),
            balance_before - deduction
        );
    end loop;

    update public.payroll_periods
    set status = 'finalized', finalized_by = p_actor_id, finalized_at = now()
    where id = p_period_id;

    insert into public.payroll_audit (payroll_period_id, actor_id, action, details)
    values (
        p_period_id, p_actor_id, 'finalized',
        jsonb_build_object('settle_overdraft', p_settle_overdraft)
    );

    return jsonb_build_object('period_id', p_period_id, 'status', 'finalized');
end;
$$;

revoke all on function public.finalize_payroll_period(bigint, uuid, boolean)
    from public, anon, authenticated;
grant execute on function public.finalize_payroll_period(bigint, uuid, boolean)
    to service_role;
